### ISSUE TITLE
where does SkipGrpcNativeLibsCopy go 

### ISSUE THREAD

**Issue by Seabizkit** [vivainio/GrpcNativeLibsCopier#1]
Hi

where is this Directory.Build.props file

-->Modify your Directory.Build.props file by adding the following rule:

even in your sample its no where

**Comment by vivainio** [comment]
Updated readme. You can add it to your "normal" csproj file if you only have one

**Comment by Seabizkit** [comment]
![image](https://user-images.githubusercontent.com/1920090/90134918-2d0c1c00-dd72-11ea-95fe-19c4fa906e81.png)

this does not change anything wen rebuilding... is it added in the correct place

**Comment by vivainio** [comment]
It's added in correct place. Ensure you have up to date Grpc.Core version

**Comment by Seabizkit** [comment]
i will double check this all when i have a sec but Im 100% sure its the latest versions... i will revert, when i have tested one more time.

**Comment by Seabizkit** [comment]
seem like i needed to restart or something as its not happening any more... will reopen if it starts again.
